Watching for file changes with StatReloader
Not Found: /docs
"GET /docs HTTP/1.1" 404 2424
Index page accessed
Internal Server Error: /main/
Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw1app\views.py", line 15, in main
    return render(request, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw1app/main.html
"GET /main/ HTTP/1.1" 500 79719
Index page accessed
Internal Server Error: /main/
Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw1app\views.py", line 15, in main
    return render(request, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw1app/main.html
"GET /main/ HTTP/1.1" 500 79856
Index page accessed
Internal Server Error: /about/
Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw1app\views.py", line 21, in about
    return render(request, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw1app/about.html
"GET /about/ HTTP/1.1" 500 78871
Index page accessed
Internal Server Error: /about/
Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw1app\views.py", line 21, in about
    return render(request, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw1app/about.html
"GET /about/ HTTP/1.1" 500 78597
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2394
Index page accessed
Internal Server Error: /about/
Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw1app\views.py", line 21, in about
    return render(request, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw1app/about.html
"GET /about/ HTTP/1.1" 500 78871
"GET /admin HTTP/1.1" 301 0
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4158
"GET /static/admin/css/base.css HTTP/1.1" 200 21544
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
"GET /static/admin/css/login.css HTTP/1.1" 200 958
"GET /static/admin/css/responsive.css HTTP/1.1" 200 17905
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
"GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2682
"GET /static/admin/js/theme.js HTTP/1.1" 200 1943
Index page accessed
Internal Server Error: /about/
Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw1app\views.py", line 21, in about
    return render(request, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw1app/about.html
"GET /about/ HTTP/1.1" 500 79472
Index page accessed
Internal Server Error: /about/
Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw1app\views.py", line 21, in about
    return render(request, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw1app/about.html
"GET /about/ HTTP/1.1" 500 79198
Index page accessed
Internal Server Error: /main/
Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw1app\views.py", line 15, in main
    return render(request, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw1app/main.html
"GET /main/ HTTP/1.1" 500 80594
Index page accessed
Internal Server Error: /main/
Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw1app\views.py", line 15, in main
    return render(request, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hw1app/main.html
"GET /main/ HTTP/1.1" 500 80320
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2394
Not Found: /docs
"GET /docs HTTP/1.1" 404 2424
Index page accessed
"GET /main/ HTTP/1.1" 200 183
Index page accessed
"GET /main/ HTTP/1.1" 200 183
Index page accessed
"GET /about/ HTTP/1.1" 200 176
Index page accessed
"GET /about/ HTTP/1.1" 200 176
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2394
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hwproject\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /hw2
"GET /hw2 HTTP/1.1" 404 2525
Internal Server Error: /hw2/customer_ordered_products/
Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\views.py", line 18, in customer_ordered_products
    return render(request, 'orders/customer_ordered_products.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: orders/customer_ordered_products.html
"GET /hw2/customer_ordered_products/ HTTP/1.1" 500 89802
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /hw2/customer_ordered_products/ HTTP/1.1" 200 9282
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /hw2/customer_ordered_products/
Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2112, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Alex'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\views.py", line 9, in customer_ordered_products
    orders_last_7_days = OrderModel.objects.filter(customer_id=client_id, date_order__gte=timezone.now() - timedelta(days=7))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1602, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1634, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1548, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1378, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\fields\related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aleksei\data\Pycharm\Django_Hw\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2114, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'Alex'.
"GET /hw2/customer_ordered_products/ HTTP/1.1" 500 128206
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /hw2/customer_ordered_products/ HTTP/1.1" 200 6135
"GET /hw2/customer_ordered_products/ HTTP/1.1" 200 6135
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /hw2/customer_ordered_products/ HTTP/1.1" 200 2277
"GET /hw2/customer_ordered_products/ HTTP/1.1" 200 2277
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /hw2/customer_ordered_products/ HTTP/1.1" 200 828
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /hw2/history_of_orders/ HTTP/1.1" 200 828
"GET /hw2/history_of_orders/ HTTP/1.1" 200 828
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /hw2/history_of_orders/ HTTP/1.1" 200 1248
C:\Users\Aleksei\data\Pycharm\Django_Hw\hwproject\hw2app\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /hw2/history_of_orders/ HTTP/1.1" 200 2277
